[env]
# QEMU
# provide path to our custom qemu version
CUSTOM_QEMU_DIR = { value = "qemu-libafl-bridge", relative = true }
# speed
NUM_JOBS = "32" # speed

# comment out to prevent qemu from randomly rebuild
#CUSTOM_QEMU_NO_BUILD = "1"
# comment out to prevent qemu from randomly configuring
#CUSTOM_QEMU_NO_CONFIGURE = "1"
#QEMU_LOG = "in_asm"

# LibAFL
#LIBAFL_DEBUG_OUTPUT = "1"
#RUST_LOG = "debug"
