[env]
# provide path to our custom qemu version
CUSTOM_QEMU_DIR = { value = "qemu-libafl-bridge", relative = true }
# comment out to prevent qemu from randomly rebuild
#CUSTOM_QEMU_NO_BUILD = "1"
# comment out to prevent qemu from randomly configuring
#CUSTOM_QEMU_NO_CONFIGURE = "1"
# firmware path
KERNEL = "./qdsp6sw.mbn"
# speed
NUM_JOBS = "32"

#QEMU_LOG = "in_asm"

#enable verbose libafl debugging
LIBAFL_DEBUG_OUTPUT = "1"
RUST_LOG = "debug"
